import type { KgCatalogue, KgCostAuthority, KgServiceAuthority, KgSourceBaseline } from './kgConfiguration'

/**
 * Schnittstellen & Verantwortung — the Option's interface/responsibility truth
 * (VR3-TGA-UX-00, `responsibility-matrix-relocation-map.md`).
 *
 * WHAT MOVED, AND WHY IT IS NOT A SECOND OWNER.
 *
 * Until this ticket the responsibility matrix was the eighth "system" of the
 * KG 400 chapter: two read-only services (`a/b-400-13g` Leistungsgrenze TGA,
 * `a/b-400-14` Hausanschlüsse) whose value rows carried the four utility
 * media. A salesperson does not configure it the way they configure a heat
 * generator — it is a statement about who delivers up to where — so it was
 * misclassified, and it inflated the chapter the audit measured. It now lives
 * in three places, each with ONE job:
 *
 * 1. the CATALOGUE (`KgCatalogue.responsibility`, generated by
 *    `tools/build_kg_fixture.py` from the same data the retired services
 *    carried): labels, values, source, cost authority, offer note — project
 *    facts;
 * 2. the OPTION RECORD (`OptionConfig.responsibility`, this module's
 *    `OptionResponsibility`): what the Option holds about each medium, seeded
 *    from the catalogue when the Option is created, versioned and persisted —
 *    the ONE editable owner;
 * 3. the PROJECTION (`responsibilityProjection` below): catalogue + record,
 *    resolved once, read by the dedicated Configurator step, by the KG 400
 *    Rahmen band's read-only boundary line, by the review and by every output.
 *
 * LOSSLESS BY CONSTRUCTION. The retired services were `readOnlyRequired`,
 * `baseline: 'selected'` and carried no user-editable state beyond
 * `{ state: 'selected' }`; every datum they showed is catalogue data. Seeding
 * the record from the catalogue therefore IS the migration, and it is
 * idempotent: seeding twice yields the same record.
 *
 * LEGACY IS ONE ADAPTER, NOT A SECOND OWNER. An Option persisted before this
 * contract has `responsibility: null`. `responsibilityProjection` answers for
 * it by seeding from the catalogue — the same function, the same result the
 * record would hold — and flags `origin: 'legacy'` so a reader can tell the
 * difference. Nothing writes the record back on read; a sent snapshot stays a
 * snapshot (M-3).
 *
 * NO EURO. `Hausanschlüsse` is the Bauherr's (`costAuthority: 'bauherr'`),
 * the boundary carries `none`. Neither produces a `Driver`, a contribution or
 * a total — exactly as before the move (the QA-01 guard in `kgContributions`
 * already dropped them). An unresolved medium is a CONDITION the offer names,
 * never an amount and never a gap.
 *
 * PURE ON PURPOSE: no store, no React, no DOM.
 */

/** The four utility media, in the order the matrix reads them. Stable IDs, never labels. */
export const RESPONSIBILITY_MEDIA = [
  'potableWater', 'foulWater', 'electricityLv', 'telecommunications',
] as const

export type ResponsibilityMediumId = typeof RESPONSIBILITY_MEDIA[number]

/** Settled, or still owing a clarification. Never colour-only in the UI. */
export type ResponsibilityStatus = 'ok' | 'attention'

/* ── the catalogue side ──────────────────────────────────────────────────── */

export type ResponsibilityMediumCatalogue = Readonly<{
  id: ResponsibilityMediumId
  labelDe: string
  labelEn: string
  /** What the client delivers, up to where — `Bauherr bis Grundstücksgrenze`. */
  clientDe: string
  clientEn: string
  status: ResponsibilityStatus
}>

export type ResponsibilityCatalogue = Readonly<{
  version: number
  scopeBoundary: Readonly<{
    labelDe: string
    labelEn: string
    summaryDe: string
    summaryEn: string
    /** The handover point — the one fact KG 400 still reads, read-only. */
    handoverDe: string
    handoverEn: string
    scopeDe: string
    scopeEn: string
    authority: KgServiceAuthority
    costAuthority: KgCostAuthority
    source: KgSourceBaseline
  }>
  connections: Readonly<{
    labelDe: string
    labelEn: string
    summaryDe: string
    summaryEn: string
    /** `Übergabepunkt` — where All3 takes over, for every medium. */
    all3FromDe: string
    all3FromEn: string
    scopeDe: string
    scopeEn: string
    authority: KgServiceAuthority
    costAuthority: KgCostAuthority
    source: KgSourceBaseline
    media: readonly ResponsibilityMediumCatalogue[]
    offerNoteDe: string
    offerNoteEn: string
  }>
}>

/* ── the Option side ─────────────────────────────────────────────────────── */

/** Bumped only when the RECORD's shape changes; the catalogue has its own version. */
export const RESPONSIBILITY_RECORD_VERSION = 1

export type ResponsibilityMediumRecord = Readonly<{
  status: ResponsibilityStatus
  /** A clarification the seller recorded. Absent until one exists. */
  note?: string
}>

/**
 * The Option-owned record — the ONE editable owner of responsibility truth.
 *
 * It holds exactly what an Option can hold ABOUT the project's matrix: the
 * per-medium status (and a note, when one is ever recorded). Labels, values,
 * sources and cost authority are catalogue facts and are not copied here —
 * copying them would be the second source of truth this module exists to
 * avoid. `seededFrom` records which catalogue version produced the seed, so a
 * later catalogue change is detectable rather than silent.
 */
export type OptionResponsibility = Readonly<{
  version: typeof RESPONSIBILITY_RECORD_VERSION
  seededFrom: number
  media: Readonly<Record<ResponsibilityMediumId, ResponsibilityMediumRecord>>
}>

/** The seed — and, for a legacy Option, the migration. Idempotent. */
export function initialResponsibility(
  catalogue: KgCatalogue | null,
): OptionResponsibility | null {
  const block = catalogue?.responsibility
  if (!block) return null
  const media = {} as Record<ResponsibilityMediumId, ResponsibilityMediumRecord>
  for (const medium of block.connections.media) {
    media[medium.id] = { status: medium.status }
  }
  return { version: RESPONSIBILITY_RECORD_VERSION, seededFrom: block.version, media }
}

/**
 * Is this a record this module can read? Persisted payloads are validated at
 * the boundary (`store.ts`), and this is the shape check they call.
 */
export function isOptionResponsibility(value: unknown): value is OptionResponsibility {
  if (typeof value !== 'object' || value === null) return false
  const record = value as Record<string, unknown>
  if (record.version !== RESPONSIBILITY_RECORD_VERSION) return false
  if (typeof record.seededFrom !== 'number') return false
  const media = record.media
  if (typeof media !== 'object' || media === null) return false
  const entries = Object.entries(media as Record<string, unknown>)
  if (entries.length !== RESPONSIBILITY_MEDIA.length) return false
  return entries.every(([id, entry]) => {
    if (!(RESPONSIBILITY_MEDIA as readonly string[]).includes(id)) return false
    if (typeof entry !== 'object' || entry === null) return false
    const medium = entry as Record<string, unknown>
    return (medium.status === 'ok' || medium.status === 'attention')
      && (medium.note === undefined || typeof medium.note === 'string')
  })
}

/* ── the projection ──────────────────────────────────────────────────────── */

export type ResponsibilityMediumProjection = Readonly<{
  id: ResponsibilityMediumId
  labelDe: string
  labelEn: string
  clientDe: string
  clientEn: string
  all3FromDe: string
  all3FromEn: string
  status: ResponsibilityStatus
  note: string | null
}>

export type ResponsibilityProjection = Readonly<{
  /** `record`: the Option's own record. `legacy`: seeded on read for an Option persisted before the record existed. */
  origin: 'record' | 'legacy'
  scopeBoundary: ResponsibilityCatalogue['scopeBoundary']
  connections: Omit<ResponsibilityCatalogue['connections'], 'media'>
  media: readonly ResponsibilityMediumProjection[]
  /** Media still owing a clarification, in matrix order. */
  unresolved: readonly ResponsibilityMediumProjection[]
}>

/**
 * Catalogue + record → the one shape every consumer reads.
 *
 * `null` when the project declares no responsibility block at all — the
 * honest answer for a directly driven store, and the state in which the
 * dedicated step renders its own "nothing to show" rather than a fabricated
 * matrix.
 */
export function responsibilityProjection(
  catalogue: KgCatalogue | null,
  record: OptionResponsibility | null,
): ResponsibilityProjection | null {
  const block = catalogue?.responsibility
  if (!block) return null
  const resolved = record ?? initialResponsibility(catalogue)
  if (!resolved) return null
  const { media: _catalogueMedia, ...connections } = block.connections
  const media = block.connections.media.map((medium): ResponsibilityMediumProjection => {
    const held = resolved.media[medium.id]
    return {
      id: medium.id,
      labelDe: medium.labelDe,
      labelEn: medium.labelEn,
      clientDe: medium.clientDe,
      clientEn: medium.clientEn,
      all3FromDe: block.connections.all3FromDe,
      all3FromEn: block.connections.all3FromEn,
      // The record wins where it exists: it is the owner. The catalogue's
      // status is the seed and the fallback for a medium the record does not
      // know yet (a catalogue that grew a fifth medium after the seed).
      status: held?.status ?? medium.status,
      note: held?.note ?? null,
    }
  })
  return {
    origin: record ? 'record' : 'legacy',
    scopeBoundary: block.scopeBoundary,
    connections,
    media,
    unresolved: media.filter((medium) => medium.status === 'attention'),
  }
}

/**
 * The fingerprint the review records — every fact the section shows, in
 * order, so a changed status reopens exactly this section (VR3-04's per-
 * section fingerprint discipline).
 */
export function responsibilityFingerprint(
  projection: ResponsibilityProjection | null,
): string {
  if (!projection) return 'none'
  return [
    projection.origin,
    projection.scopeBoundary.handoverDe,
    ...projection.media.map((medium) =>
      `${medium.id}=${medium.status}${medium.note ? `:${medium.note}` : ''}`),
  ].join('|')
}
