/**
 * VR3 — the project's SOURCE DOCUMENTS, as real files.
 *
 * The document register used to preview a document by pointing at an image
 * asset, and six schematic SVGs served thirty-six records: opening
 * `01_Auftraggeberbrief_Quartier.pdf` produced a stylised block plan with
 * clipped labels, and two unrelated documents produced the same picture. A
 * register whose evidence is interchangeable is not evidence.
 *
 * So a document now resolves to a FILE — an internally authored, synthetic,
 * multi-page PDF, generated by `tools/build_leipzig_documents.py` and
 * registered with full provenance in
 * `design-system/assets/documents/manifest.json`. The lookup key is the
 * document id, the filename comes from the manifest next to the files, and
 * the URL comes from the bundler. There is no string path in component code:
 * renaming a file breaks the build, not the rendering — the same reasoning as
 * `project-media.ts` and `option-images.ts`.
 *
 * TOLERANT BY CONSTRUCTION, deliberately. Both globs may match nothing — a
 * checkout that has not generated the pack yet, or a document with no file
 * registered — and every entry point then returns `null`. `null` is a REAL
 * product state (`unavailable`), not an error to be swallowed: the viewer
 * renders the filename, the reason and a way back rather than collapsing.
 * The alternative, a static import of the manifest, would make a missing
 * generated artefact a build failure in a checkout that is otherwise fine.
 */

type ManifestAnchor = {
  id: string
  page: number
  labelDe: string
  labelEn: string
}

type ManifestDocument = {
  id: string
  file: string
  title: string
  documentType: string
  revision: string
  pages: number
  issuedAt: string
  /** `internal synthetic` — the only provenance this pack may declare. */
  origin: string
  author: string
  createdAt: string
  approvedClientDemoUse: boolean
  licence: string
  intendedUse: string
  demoFixture: boolean
  projectLevel: boolean
  buildingIds: string[]
  anchors: ManifestAnchor[]
}

/**
 * A re-sent copy: the SAME bytes under the name a mail client produced on the
 * second send. It is not a thirteenth authored document and the manifest does
 * not list it as one — it names the file it duplicates, and this module folds
 * it into the lookup so that opening the duplicate row opens the very file it
 * is a duplicate of. Anything else would make the register's «inhaltsgleiches
 * Doppel» unverifiable at exactly the moment a reader tries to verify it.
 */
type ManifestDuplicate = {
  id: string
  duplicateOf: string
  file: string
  uploadName: string
  receivedAt: string
  pages: number
}

type DocumentManifest = {
  generator: string
  documents: ManifestDocument[]
  duplicates?: ManifestDuplicate[]
  anchorCount: number
}

const MANIFESTS = import.meta.glob(
  '../../design-system/assets/documents/manifest.json',
  { eager: true, import: 'default' },
) as Record<string, DocumentManifest>

const MANIFEST: DocumentManifest | null =
  Object.values(MANIFESTS)[0] ?? null

const FILES = import.meta.glob(
  '../../design-system/assets/documents/leipzig/*.pdf',
  { eager: true, query: '?url', import: 'default' },
) as Record<string, string>

/**
 * Keyed by BASENAME on both sides.
 *
 * The manifest records `file` relative to its own directory
 * (`leipzig/09_TGA_Anforderungen_RevC.pdf`) and the glob returns a path
 * relative to this module. Comparing the two verbatim never matches, and the
 * symptom is the viewer's `unavailable` state on a file that is right there
 * on disk — a state that looks exactly like the honest one. Reducing both
 * sides to the filename is the one place that reconciliation happens.
 */
const basename = (path: string): string => path.split('/').pop()!

const BY_NAME = new Map(
  Object.entries(FILES).map(([path, url]) => [basename(path), url]),
)

const INDEX = new Map<string, ManifestDocument>(
  (MANIFEST?.documents ?? []).map((entry) => [entry.id, entry]),
)

/*
 * A duplicate inherits the authored entry it copies — same file, same pages,
 * same anchors, because it IS that document — and keeps its own id so the
 * register can address the two records separately. `duplicates` is optional
 * in the type on purpose: a pack generated before this section existed is a
 * valid pack, and must not turn every document into `unavailable`.
 */
for (const copy of MANIFEST?.duplicates ?? []) {
  const source = INDEX.get(copy.duplicateOf)
  if (source) INDEX.set(copy.id, { ...source, id: copy.id })
}

export type DocumentAsset = {
  documentId: string
  file: string
  /** Serviceable URL for the PDF itself. */
  url: string
  pages: number
  revision: string
  issuedAt: string
  origin: string
  author: string
  approvedClientDemoUse: boolean
}

/**
 * The registered file for a document id, or `null` when the id is unknown or
 * its file is missing. The caller renders the viewer's `unavailable` state —
 * never a silent gap and never an empty box.
 */
export function documentAsset(documentId: string): DocumentAsset | null {
  const entry = INDEX.get(documentId)
  if (!entry) return null
  const url = BY_NAME.get(basename(entry.file))
  if (!url) return null
  return {
    documentId: entry.id,
    file: entry.file,
    url,
    pages: entry.pages,
    revision: entry.revision,
    issuedAt: entry.issuedAt,
    origin: entry.origin,
    author: entry.author,
    approvedClientDemoUse: entry.approvedClientDemoUse,
  }
}

/**
 * One cited anchor, resolved against the manifest — the page it sits on and
 * its label in both languages.
 *
 * The label is NOT an i18n key: it names a clause in a specific synthetic
 * document, so it belongs with the document, and the manifest carries `de`
 * and `en` side by side for exactly that reason.
 */
export type DocumentAnchor = {
  id: string
  page: number
  labelDe: string
  labelEn: string
}

export function documentAnchor(
  documentId: string,
  anchorId: string,
): DocumentAnchor | null {
  const entry = INDEX.get(documentId)
  if (!entry) return null
  return entry.anchors.find((anchor) => anchor.id === anchorId) ?? null
}

/** Every registered document id, for fixture-integrity assertions. */
export function registeredDocumentIds(): string[] {
  return (MANIFEST?.documents ?? []).map((entry) => entry.id)
}

/** The pack's declared anchor total, or `0` when no manifest is present. */
export function registeredAnchorCount(): number {
  return MANIFEST?.anchorCount ?? 0
}

/** Whether a generated pack is present in this checkout at all. */
export function documentPackPresent(): boolean {
  return MANIFEST !== null && BY_NAME.size > 0
}
